repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.10
        
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: scripts/typecheck.sh
        language: script
        pass_filenames: false
        types: [ python, pyi ]